# Generated by Django 3.1.3 on 2020-12-19 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('author', models.CharField(db_index=True, max_length=30)),
                ('bpm', models.CharField(db_index=True, max_length=30)),
                ('genre', models.CharField(db_index=True, max_length=30)),
                ('likes', models.CharField(db_index=True, max_length=30)),
                ('version', models.CharField(db_index=True, max_length=30)),
                ('identificator', models.CharField(db_index=True, max_length=30)),
                ('downloads', models.CharField(db_index=True, max_length=30)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата загрузки трека')),
            ],
        ),
        migrations.CreateModel(
            name='TopSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(db_index=True, max_length=30)),
            ],
        ),
    ]
